server:
  port: 8000

web:
  domain: 114.55.56.132
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Yy123456.
    url: jdbc:mysql://114.55.56.132:3306/historical_statistics?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: yufang-admin

logging:
  level:
    root: info
    com.ncu.building: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml